
[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-20

[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-20

[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-20

[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-20

[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-20

[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-20

[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-20

[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-20

[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-20

[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-20

[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-20

[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-20

[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-20

[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-20

[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-20

[[data]]
name = "tmux"
tags = ["soft"]
link = "https://github.com/tmux/tmux"
description = "tmux is a terminal multiplexer: it enables a number of terminals to be created, accessed, and controlled from a single screen. tmux may be detached from a screen and continue running in the background, then later reattached."
created_at = 2020-09-20

[[data]]
name = "tldr"
tags = ["soft"]
link = "https://github.com/tldr-pages/tldr"
description = "A collection of community-maintained help pages for command-line tools"
created_at = 2020-09-20

[[data]]
name = "systemd"
tags = ["soft"]
link = "https://github.com/systemd/systemd"
description = "The systemd System and Service Manager"
created_at = 2020-09-20

[[data]]
name = "Solidity"
tags = ["programming language"]
link = "https://github.com/ethereum/solidity/"
description = "Solidity is a statically typed, contract-oriented, high-level language for implementing smart contracts on the Ethereum platform."
created_at = 2020-09-20

[[data]]
name = "OpenEthereum"
tags = ["soft"]
link = "https://github.com/openethereum/openethereum"
description = "Fast and feature-rich multi-network Ethereum client."
created_at = 2020-09-20

[[data]]
name = "Midnight Commander"
tags = ["soft"]
link = "https://github.com/MidnightCommander/mc"
description = "GNU Midnight Commander (also referred to as MC) is a user shell with text-mode full-screen interface."
created_at = 2020-09-20

[[data]]
name = "Make"
tags = ["soft"]
link = "https://www.gnu.org/software/make/"
description = "Make is a tool which controls the generation of executables and other non-source files of a program from the program's source files."
created_at = 2020-09-20

[[data]]
name = "Gitea"
tags = ["soft"]
link = "https://github.com/go-gitea/gitea"
description = "Git with a cup of tea, painless self-hosted git service"
created_at = 2020-09-20

[[data]]
name = "geth"
tags = ["soft"]
link = "https://github.com/ethereum/go-ethereum"
description = "Official Go implementation of the Ethereum protocol"
created_at = 2020-09-20

[[data]]
name = "Bash"
tags = ["programming language"]
link = "https://github.com/bminor/bash"
description = "Bash is the GNU Project's Bourne Again SHell, a complete implementation of the POSIX shell spec, but also with interactive command line editing, job control on architectures that support it, csh-like features such as history substitution and brace expansion, and a slew of other features."
created_at = 2020-09-20

[[data]]
name = "aria2"
tags = ["soft"]
link = "https://github.com/aria2/aria2"
description = "aria2 is a lightweight multi-protocol & multi-source, cross platform download utility operated in command-line. It supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink."
created_at = 2020-09-20

[[data]]
name = "twine"
tags = ["pypi"]
link = "https://github.com/pypa/twine"
description = "Utilities for interacting with PyPI"
created_at = 2020-09-19

[[data]]
name = "wheel"
tags = ["pypi"]
link = "https://github.com/pypa/wheel"
description = "The official binary distribution format for Python"
created_at = 2020-09-19

[[data]]
name = "PySnooper"
tags = ["pypi"]
link = "https://github.com/cool-RR/PySnooper"
description = "Never use print for debugging again"
created_at = 2020-09-19

[[data]]
name = "pre-commit"
tags = ["pypi"]
link = "https://github.com/pre-commit/pre-commit"
description = "A framework for managing and maintaining multi-language pre-commit hooks"
created_at = 2020-09-19

[[data]]
name = "pytest"
tags = ["pypi"]
link = "https://github.com/pytest-dev/pytest"
description = "The pytest framework makes it easy to write small tests, yet scales to support complex functional testing"
created_at = 2020-09-19

[[data]]
name = "gunicorn"
tags = ["pypi"]
link = "https://github.com/benoitc/gunicorn"
description = "gunicorn 'Green Unicorn' is a WSGI HTTP Server for UNIX, fast clients and sleepy applications"
created_at = 2020-09-19

[[data]]
name = "uvicorn"
tags = ["pypi"]
link = "https://github.com/encode/uvicorn"
description = "The lightning-fast ASGI server"
created_at = 2020-09-19

[[data]]
name = "PySocks"
tags = ["pypi"]
link = "https://github.com/Anorov/PySocks"
description = "A SOCKS proxy client and wrapper for Python"
created_at = 2020-09-19

[[data]]
name = "requests"
tags = ["pypi"]
link = "https://github.com/psf/requests"
description = "A simple, yet elegant HTTP library"
created_at = 2020-09-19

[[data]]
name = "cargo-expand"
tags = ["cargo"]
link = "https://github.com/dtolnay/cargo-expand"
description = "Subcommand to show result of macro expansion"
created_at = 2020-09-19

[[data]]
name = "wrapt"
tags = ["pypi"]
link = "https://github.com/GrahamDumpleton/wrapt"
description = "A Python module for decorators, wrappers and monkey patching"
created_at = 2020-09-19

[[data]]
name = "pydash"
tags = ["pypi"]
link = "https://github.com/dgilland/pydash"
description = """The kitchen sink of Python utility libraries for doing "stuff" in a functional way. Based on the Lo-Dash Javascript library."""
created_at = 2020-09-19

[[data]]
name = "python-dotenv"
tags = ["pypi"]
link = "https://github.com/theskumar/python-dotenv"
description = "Get and set values in your .env file in local and production servers"
created_at = 2020-09-19

[[data]]
name = "PyMongo"
tags = ["pypi"]
link = "https://github.com/mongodb/mongo-python-driver"
description = "PyMongo - the Python driver for MongoDB"
created_at = 2020-09-19

[[data]]
name = "FastAPI"
tags = ["pypi", "web"]
link = "https://github.com/tiangolo/fastapi"
description = "FastAPI framework, high performance, easy to learn, fast to code, ready for production"
created_at = 2020-09-19

[[data]]
name = "postgres"
tags = ["crate"]
link = "https://github.com/sfackler/rust-postgres"
description = "PostgreSQL support for Rust."
created_at = 2020-09-19


[[data]]
name = "libs.garden"
tags = ["service"]
link = "https://libs.garden/"
description = "libraties and apps rating"
created_at = 2020-09-19


[[data]]
name = "Docker"
tags = ["devops"]
link = "https://www.docker.com/"
description = "Docker is an open platform for developing, shipping, and running applications"
created_at = 2020-09-19

[[data]]
name = "Ansible"
tags = ["devops"]
link = "https://github.com/ansible/ansible"
description = "Ansible is a radically simple IT automation system"
created_at = 2020-09-19

[[data]]
name = "PostgreSQL"
tags = ["database"]
link = "https://www.postgresql.org/"
description = "PostgreSQL is an object-relational database"
created_at = 2020-09-19

[[data]]
name = "MongoDB"
tags = ["database"]
link = "https://github.com/mongodb/mongo"
description = "MongoDB is a general purpose, document-based, distributed database"
created_at = 2020-09-19

[[data]]
name = "handlebars-rust"
tags = ["crate"]
link = "https://github.com/sunng87/handlebars-rust"
description = "Handlebars templating language implemented in Rust and for Rust"
created_at = 2020-09-19


[[data]]
name = "Visual Studio Code"
tags = ["soft"]
link = "https://code.visualstudio.com/"
description = "It's a lightweight but powerful source code editor"
created_at = 2020-09-19


[[data]]
name = "git"
tags = ["soft"]
link = "https://git-scm.com/"
description = "Git is a distributed version-control system for tracking changes in source code during software development"
created_at = 2020-09-19


[[data]]
name = "iTerm2"
tags = ["soft"]
link = "https://iterm2.com/"
description = "It's a terminal emulator for macOS"
created_at = 2020-09-19

[[data]]
name = "Docs.rs"
tags = ["service", "rust"]
link = "https://docs.rs"
description = "Docs.rs is an open source documentation host for crates of the Rust Programming Language."
created_at = 2020-09-19

[[data]]
name = "toml-rs"
tags = ["crate"]
link = "https://crates.io/crates/toml"
description = "A TOML encoding/decoding library for Rust"
created_at = 2020-09-19

[[data]]
name = "crates.io"
tags = ["service", "rust"]
link = "https://crates.io/"
description = "The Rust community’s crate registry"
created_at = 2020-09-19


[[data]]
name = "Rust"
tags = ["programming language"]
link = "https://www.rust-lang.org/"
description = "Rust is a multi-paradigm programming language focused on performance and safety, especially safe concurrency."
created_at = 2020-09-19

[[data]]
name = "Python"
tags = ["programming language"]
link = "https://www.python.org/"
description = "Python is an interpreted, high-level and general-purpose programming language."
created_at = 2020-09-19

[[data]]
name = "GitHub"
tags = ["service", "git"]
link = "https://github.com/"
description = "It provides hosting for software development and version control using Git"
created_at = 2020-09-19


[[data]]
name = "PyCharm"
tags = ["soft", "python", "ide"]
link = "https://www.jetbrains.com/pycharm/"
description = "The Python IDE"
created_at = 2020-09-19
