[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-19

[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-19

[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-19

[[data]]
name = ""
tags = []
link = ""
description = ""
created_at = 2020-09-19


[[data]]
name = "Rust"
tags = ["programming language"]
link = "https://www.rust-lang.org/"
description = "Rust is a multi-paradigm programming language focused on performance and safety, especially safe concurrency."
created_at = 2020-09-19

[[data]]
name = "Python"
tags = ["programming language"]
link = "https://www.python.org/"
description = "Python is an interpreted, high-level and general-purpose programming language."
created_at = 2020-09-19

[[data]]
name = "GitHub"
tags = ["service", "git"]
link = "https://github.com/"
description = "It provides hosting for software development and version control using Git"
created_at = 2020-09-19


[[data]]
name = "PyCharm"
tags = ["soft", "python", "ide"]
link = "https://www.jetbrains.com/pycharm/"
description = "The Python IDE"
created_at = 2020-09-19
